30days/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
]

30days/main/urls.py
from django.urls import path
from . import views

# 네임스페이스 - 별칭때문에 사용(다른 앱과 별칭이 겹칠수도 있어서)
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

30days/pybo/urls.py
from django.urls import path
from . import views

# 네임스페이스 - 별칭때문에 사용(다른 앱과 별칭이 겹칠수도 있어서)
app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

30days/pybo/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

30days/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels={
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

30days/pybo/views.py
from .models import Question
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required



def index(request):
    """
    question 목록
    """
    # GET 방식 요청 URL에서 page값을 가져올 때 사용한다.
    # (ex) localhost:8000/pybo/?page=1
    page = request.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')
    # 페이징처리
    # Paginator 클래스를 사용했으며
    # 페이지당 10개씩 보여주기
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
    question 내용
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    답변 등록 / answer 테이블에 데이터 추가
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        # get 부분이 없어도 실행은 가능
        form = AnswerForm()
        context = {'question':question, 'form':form}
        return render(request, 'pybo/question_detail.html', context)
   

@login_required(login_url='common:login')
def question_create(request):
    """
    질문 등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
        context = {'form': form}
        return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    질문 수정
    """
    question = get_object_or_404(Question, pk=question_id)
    # 현재 사용자와 글을 쓴 사람이 다를 시 다시 해당 게시글로 redirect
    if request.user != question.author:
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        # 화면으로 전달받은 입력값들을 덮어써서 QuestionForm을 생성하라는 의미
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        # instance 매개변수에 question을 지정하면 기존 값을 폼에 채울 수 있음
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    질문 삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    # 현재 사용자와 글을 쓴 사람이 다를 시 다시 해당 게시글로 redirect
    if request.user != question.author:
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

30days/templates/pybo/question_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>question_detail</title>
</head>
<body>

<div id="question_detail">

    <!--제목 출력-->
    <div id="SC">
        <h2>👉 {{question.subject}} 👈</h2>
    </div>
    <!--제목 출력 끝-->

    <hr>

    <!--글쓴이와 글쓴 날짜 출력-->
    <table id="question_information">
            <tr>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
    </table>
    <!--글쓴이와 글쓴 날짜 출력 끝-->

    <hr>

    <!--내용 출력-->
    <div id="question_content">{{question.content}}</div>
    <!--내용 출력 끝-->

    <br>

    <!--답변 등록 form-->
    <form action="{% url 'pybo:answer_create' question.id%}" method="post">
        <!--아래 태그는 항상 form 바로 아래 적어준다: 실제로 웹 브라우저에서 적힌 것인지 확인(보안)-->
        {% csrf_token %}

        <!--오류 표시-->
        {% if form.errors %}
        <div role="alert">
            {% for field in form %}
                {% if field.errors %}
                    {{ field.label }}
                    {{ field.errors}}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!--오류 표시 끝-->

        <!--답변등록-->
        <h5 id="answerComment">WRITE ANSWER HERE</h5>
        <textarea id="answerTextarea" name="content" rows="3"></textarea>
        <!--답변등록 끝-->


        <div id="answerButton">
            <!--게시판 첫 페이지로 돌아가는 버튼-->
            <button type="button" onclick="location.href='{% url 'pybo:index' %}' ">BACK</button>
            <!--답변 등록 버튼-->
            <button type="submit">SAVE</button>

            <!--현재 사용자와 글쓴이가 같다면 버튼 노출-->
            {% if request.user == question.author %}
                <!--게시글 수정 버튼-->
                <button type="button" onclick="location.href='{% url 'pybo:question_modify' question.id  %}' ">MODIFY</button>
                <!--게시글 삭제 버튼-->
                <button type="button" onclick="delete_confirm();">DELETE</button>
            {% endif %}
        </div>

    </form>
    <!--답변 등록 form 끝-->

    <hr>

    <!--답변 리스트-->
    <h5>{{question.answer_set.count}}개의 답변</h5>
    <div>
        <ul>
            {% for answer in question.answer_set.all %}
            <li id="answer">
                <table>
                    <tr>
                        <td>{{answer.content}}</td>
                    </tr>
                    <tr>
                        <td>{{ answer.create_date }}</td>
                        <td>&nbsp; |  &nbsp;</td>
                        <td>글쓴이 : {{ answer.author.username }}</td>
                    </tr>
                </table>
            </li>
            {% endfor %}
        </ul>
    </div>
    <!--답변 리스트 끝-->

</div>

<script>

    function delete_confirm(){
        if(confirm("정말 삭제하시겠습니까?") == true){
            location.href='{% url 'pybo:question_delete' question.id  %}';
        }else{
            return;
        }
    }

</script>

</body>
</html>

30days/templates/pybo/question_form.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>question_form</title>
</head>
<body>

<div id="question_form">

    <h2>📝📝📝</h2><br>

    <form method="post">
        {% csrf_token %}
        <!--{{ form.as_p }}-->

        <!--오류 표시 시작-->
        {% if form.errors %}
        <div>
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!--오류 표시 끝-->

        <div>
            <input type="text" name="subject" id="subject" placeholder="SUBJECT"
                   value="{{ form.subject.value|default_if_none:''}}"><br><br>
        </div>

        <div>
            <!--<label id="contentLbl" for="content">내용</label><br>-->
            <textarea id="contentTextarea" name="content" rows="20">
                {{form.content.value|default_if_none:''}}
            </textarea>
        </div>

        <br><br>

        <button type="submit">SAVE</button>
        <button type="button" onclick="location.href='{% url 'pybo:index' %}' ">BACK</button>

    </form>

</div>

</body>
</html>

30days/templates/pybo/question_list.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>question_list</title>
</head>
<body>

<div id="question_list">

    <h2>📂📂📂</h2>

    <!-- 질문 목록-->
    <table id="QList">

        <thead>
        <tr>
            <th>번호</th>
            <th>제목</th>
            <th>답변수</th>
            <th>글쓴이</th>
        </tr>
        </thead>

        <tbody>
        {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td style="text-align: left"><a href="{% url 'pybo:detail' question.id %}">{{question.subject}}</a></td>
                <td>{{ question.answer_set.count }}</td>
                <td>{{ question.author.username }}</td>
            </tr>
            {% endfor %}
        {% else %}
        <p> 등록된 질문이 없습니다.</p>
        {% endif %}
        </tbody>

    </table>
    <!-- 질문 목록 끝-->


    <br>

    <!-- 페이징처리 시작 -->
    <ul class="paging">

        <!-- 이전페이지 -->
        <!-- 이전 페이지가 있다면 '이전' 링크가 활성화되지만, 반대로 이전 페이지가 없으면 '이전' 링크는 비활성화-->
        {% if question_list.has_previous %}
        <li class="page-link">
            <a href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-link">
            <a href="#">이전</a>
        </li>
        {% endif %}
        <!-- 이전페이지 끝 -->

        <!-- 주요속성 -->
        <!-- .page_range : 전체 페이지 번호-->
        <!-- .number : 현재 페이지 번호-->
        <!-- .previous_page_number : 이전 페이지 번호 -->
        <!-- .next_page_number : 다음 페이지 번호 -->

        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
            <!-- 현재페이지에서 -5한 수와 +5한 페이지를 포함한 사이에 있는 페이지만 출력 -->
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                <!-- if문이 없을 시에는 현재페이지만 출력 -->
                {% if page_number == question_list.number %}
                <li class="page-link">
                    <a href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-link">
                    <a href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 페이지리스트 끝-->

        <!-- 다음페이지 -->
        <!-- 다음 페이지가 있다면 '다음' 링크가 활성화되지만, 반대로 다음 페이지가 없으면 '다음' 링크는 비활성화-->
        {% if question_list.has_next %}
        <li class="page-link">
            <a href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-link">
            <a href="#">다음</a>
        </li>
        {% endif %}
        <!-- 다음페이지 끝-->

    </ul>
    <!-- 페이징처리 끝 -->


    <br>

    <!--질문 등록 버튼-->
    <button type="button" onClick="location.href='{% url 'pybo:question_create' %}'">REGISTER</button>
    <!--메인화면 이동 버튼-->
    <button type="button" onClick="location.href='{% url 'main:index' %}'">MAINPAGE</button>

</div>

</body>
</html>