30days/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('check/', views.check, name='check'),
    path('addition/', views.addition, name='addition'),
]

30days/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
]

30days/main/urls.py
from django.urls import path
from . import views

# 네임스페이스 - 별칭때문에 사용(다른 앱과 별칭이 겹칠수도 있어서)
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

30days/common/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #기초대사량
    RMR = models.FloatField()
    #권장칼로리
    RC = models.FloatField()
    #자신이 하고자하는 운동 시간
    exercise = models.FloatField()

30days/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from common.models import Profile


class UserForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['RMR', 'RC', 'exercise']

30days/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from common.forms import ProfileForm
from django.contrib.auth.decorators import login_required


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('common:addition')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def check(request):
    """
    가입 전 비만검사
    """
    return render(request, 'common/check.html')


@login_required(login_url='common:login')
def addition(request):
    """
    가입 후 기초대사랑, 권장대사량, 자신이 매일 하고자 하는 운동 시간
    """
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('main:index')
    else:
        form = ProfileForm()
        return render(request, 'common/addition.html', {'form': form})

30days/templates/common/addition.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>addition</title>
</head>
<body>

<div id="addition">
    <!--<h2>✋ 사전정보입력 ✋</h2>-->
    <!-- <hr>-->

    <div id="container">
        <div id="addition_cal">
            <!--기초대사량과 권장칼로리 계산기-->
            <h4>✋ 기초대사량 & 권장칼로리 계산기 ✋</h4>

            <table>
                <tr>
                    <td><strong>성별</strong></td>
                    <td><input type="radio" name="gender" value="man">남자 <input type="radio" name="gender" value="woman">여자
                    </td>
                </tr>

                <tr>
                    <td><strong>나이</strong></td>
                    <td><input type="text" id="age"></td>
                </tr>

                <tr>
                    <td><strong>신장</strong></td>
                    <td><input type="text" id="height" placeholder="CM"></td>
                </tr>

                <tr>
                    <td><strong>체중</strong></td>
                    <td><input type="text" id="weight" placeholder="KG"></td>
                </tr>

                <tr>
                    <td><strong>활동지수</strong></td>
                    <td>
                        <input type="radio" name="num" value="1.2">운동을 따로 하지 않는 경우 <br>
                        <input type="radio" name="num" value="1.375">격렬한 운동 주 1~2회 or 가벼운 운동 3~4회 <br>
                        <input type="radio" name="num" value="1.425">격렬한 운동 주 3~4회 or 가벼운 운동 5~7회 <br>
                        <input type="radio" name="num" value="1.55">격렬한 운동 주 5~6회 <br>
                        <input type="radio" name="num" value="1.75">격렬한 운동 주 6~7회
                    </td>
                </tr>

                <tr>
                    <td style="text-align: center;" colspan="2"><button type="button" onclick="cal()">계산하기</button></td>
                </tr>
            </table>
        </div>


        <div id="addition_form">
            <h4>✋ 사전 정보 저장 ✋</h4>
            <!--profile 모델에 저장하는 form-->
            <form method="post">
                {% csrf_token %}
                {% include "form_errors.html" %}

                <table>
                    <tr>
                        <td><strong>기초대사량</strong></td>
                        <td><input type="text" name="RMR" id="RMR" value="{{ form.RMR.value|default_if_none:'' }}"></td>
                    </tr>

                    <tr>
                        <td><strong>권장칼로리</strong></td>
                        <td><input type="text" name="RC" id="RC" value="{{ form.RC.value|default_if_none:'' }}"></td>
                    </tr>

                    <tr>
                        <td><strong>목표 하루 운동시간</strong></td>
                        <td><input type="text" name="exercise" id="exercise" placeholder="MINUTE" value="{{ form.exercise.value|default_if_none:'' }}"></td>
                    </tr>

                    <tr>
                        <td style="text-align: center;" colspan="2"><button type="submit">SAVE</button></td>
                    </tr>
                </table>

            </form>
        </div>
    </div>

    <!--<div id="addition_intro">
        <p>저희 작심삼십일에서는 하루에 섭취하는 칼로리의 기준을 기초대사량 < 하루 섭취한 칼로리 < 권장칼로리로 하고 있습니다.</p>
        <p>위의 기준을 참고하시고 정보를 입력해주세요.</p>
        <p>만약 정확한 측정결과가 없다면 아래의 계산기를 이용해 보세요!</p>
    </div>-->

    <details id="additionDetails">
        <summary>기초대사량과 권장칼로리를 작성하는 이유는?</summary>
            <p>기초대사량보다 칼로리를 적게 섭취한다면 오히려 몸이 위급한 상황이라고 생각해 먹는 족족 지방으로 변환시킵니다.</p>
            <p>또한 권장칼로리보다 많이 섭취하게 된다면 체중이 증가합니다. 그렇기 때문에</p>
            <p>저희 작심삼십일에서는 하루에 섭취하는 칼로리의 기준을 기초대사량 < 하루 섭취한 칼로리 < 권장칼로리로 하고 있습니다.</p>
            <p>위의 기준을 참고하시고 정보를 입력해주세요.</p>
            <p>만약 정확한 측정결과가 없다면 아래의 계산기를 이용해 보세요!</p>
    </details>

</div>

    <!--기초대사량과 권장칼로리 계산기 구현-->
    <script>

        function cal(){

            var resultRMR, resultRC;
            var age = document.getElementById("age").value;
            var weight = document.getElementById("weight").value;
            var height = document.getElementById("height").value;
            var obj_length_gender = document.getElementsByName("gender").length;
            var obj_length_num = document.getElementsByName("num").length;


            for (var i=0; i<obj_length_gender; i++) {
                if (document.getElementsByName("gender")[i].checked == true) {
                    if(document.getElementsByName("gender")[i].value == "man"){
                        resultRMR = 66.47+(13.75*weight)+(5*height)-(6.76*age);
                    }else{
                        resultRMR = 655.1+(9.56*weight)+(1.85*height)-(4.68*age);
                    }
                }
            }

            for (var i=0; i<obj_length_gender; i++) {
                if (document.getElementsByName("num")[i].checked == true) {
                    resultRC = document.getElementsByName("num")[i].value*resultRMR;
                }
            }

            document.getElementById("RMR").value = resultRMR;
            document.getElementById("RC").value = resultRC;
            console.log(age);
            console.log(weight);
            console.log(height);
        }

    </script>

</body>
</html>

30days/templates/common/check.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>check</title>
</head>
<body>

<div id="check">

    <div id="check_cal1">
        <!-- BMI 계산기 start -->
        <h3 id="BMIcalComment">🖐 BMI 계산기 🖐</h3>

        <input type="text" id="weight" placeholder="WEIGHT">
        <input type="text" id="height" placeholder="HEIGHT">

        <button type="button" onclick="BMIcal()">계산하기</button> <br>
    </div>

    <div id="check_cal2">
        <h5>당신의 BMI 결과는</h5>
        <input type="text" id="result">
        <h5>입니다. </h5>
        <!-- BMI 계산기 end -->

        <!-- 지수 나타내기 -->
        <h5 id="index"></h5>
    </div>

    <div>
         <!-- 회원가입 버튼 -->
         <button type="button" id="joinBtn" value="회원가입" onclick="location.href='{% url 'common:signup' %}'" style="display:none;">회원가입</button>
    </div>

    <!--<div id="check_intro">
        <p>BMI 검사의 정확한 명칭은 신체질량지수(Body Mass Index)로 신장과 체중의 비율을 사용한 체중의 객관적인 지수를 말합니다.</p>
        <p>저희 작심삼십일은 BMI 검사 결과가 비만/고도비만/초고도비만 인분들만 회원가입을 진행하실 수 있습니다. </p>
    </div>-->

    <details id="checkDetails">
        <summary>회원가입 전 BMI검사를 진행하는 이유는?</summary>
            <p>BMI 검사의 정확한 명칭은 신체질량지수(Body Mass Index)로 신장과 체중의 비율을 사용한 체중의 객관적인 지수를 말합니다.<br>
               저희 작심삼십일은 BMI 검사 결과가 비만/고도비만/초고도비만인 분들만 회원가입을 진행하실 수 있습니다. </p>
    </details>

</div>

    <script>

        var result;
        var joinButton = document.getElementById("joinBtn");

        function BMIcal(){
            var weight = document.getElementById("weight").value;
            var height = document.getElementById("height").value;

            if(weight == 0 || height == 0){
                result = "";
                alert("다시 입력해주세요.");
            }else{
                result = weight/(height*height*0.0001);
                index();
            }

            document.getElementById("result").value = result;
        }


        function index(){
            if(result >= 35){
                document.getElementById("index").innerHTML="초고도비만입니다.";
                joinButton.style.display="block";

            }else if(result >= 30){
                document.getElementById("index").innerHTML="고도비만입니다.";
                joinButton.style.display="block";

            }else if(result >= 25){
                document.getElementById("index").innerHTML="고도비만입니다.";
                joinButton.style.display="block";

            }else{
                document.getElementById("index").innerHTML="가입조건에 맞지않습니다.";
                joinButton.style.display="none";
            }

        }

    </script>

</body>
</html>

30days/templates/common/login.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>login</title>
</head>
<body>

<div id="login_parent">
<div id="login">

    <h2>🔒🔑🔓</h2>

    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div>
            <input type="text" name="username" id="username" placeholder="USERNAME"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div>
            <input type="password" name="password" id="password" placeholder="PASSWORD"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>

        <br>
        <button type="button" onclick="location.href='{% url 'common:check' %}' ">회원가입</button>
        <button type="submit">로그인</button>
    </form>

</div>
</div>

</body>
</html>

30days/templates/common/signup.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>signup</title>
</head>
<body>

<div id="signup">

    <h2>🙌 MEMBER JOIN 🙌</h2>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}

        <table>
            <tr>
                <td><strong>USER ID</strong></td>
                <td><input type="text" name="username" id="userID"
                           value="{{ form.username.value|default_if_none:'' }}"></td>
            </tr>

            <tr>
                <td><strong>PASSWORD</strong></td>
                <td><input type="password" name="password1" id="password1"
                           value="{{ form.password1.value|default_if_none:'' }}"></td>
            </tr>

            <tr>
                <td><strong>PASSWORD CHECK</strong></td>
                <td><input type="password" name="password2" id="password2"
                           value="{{ form.password2.value|default_if_none:'' }}"></td>
            </tr>

            <tr>
                <td><strong>EMAIL</strong></td>
                <td><input type="text" name="email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}"></td>
            </tr>

            <tr>
                <td colspan="2" style="text-align: center;"><button type="submit">SIGN UP</button></td>
            </tr>

        </table>

    </form>

</div>

</body>
</html>