30days/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('check/', views.check, name='check'),
    path('addition/', views.addition, name='addition'),
]

30days/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', include('main.urls')),
    path('record/', include('record.urls')),
]

30days/main/urls.py
from django.urls import path
from . import views

# 네임스페이스 - 별칭때문에 사용(다른 앱과 별칭이 겹칠수도 있어서)
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

30days/pybo/urls.py
from django.urls import path
from . import views

# 네임스페이스 - 별칭때문에 사용(다른 앱과 별칭이 겹칠수도 있어서)
app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

30days/record/urls.py
from django.urls import path
from . import views

app_name = 'record'

urlpatterns = [
    path('', views.index, name='index'),
    path('before', views.before, name='before'),
    path('after', views.after, name='after'),
]

30days/templates/base.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>base</title>
</head>
<body>
<!--기본 템플릿 안에 삽입될 내용 시작-->
{% block content %}
{% load static %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 끝-->
</body>
</html>

30days/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div>
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div>
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

30days/templates/mainPage.html
<!DOCTYPE html>
 {% load static %}
<html lang="ko">
<head>
    <!--meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>mainPage</title>
</head>
<body>

    <div id="mainLogo">
        <img id="logo" src="{% static 'img/logoB.png' %}">
    </div>


    <!-- 네비게이션바 -->
    <nav id="mainNav">
        <!-- 로그인 -->
        {% if user.is_authenticated %}
            <button type="button" onclick="location.href='{% url 'common:logout' %}' ">LOGOUT</button>
            <button type="button" onclick="location.href='{% url 'record:index' %}'">{{ user.username }}님의 기록</button>
            <button type="button" onclick="location.href='{% url 'pybo:index' %}' ">Q&A</button>
        {% else %}
            <button type="button" onclick="location.href='{% url 'common:login' %}' ">LOGIN</button>
            <button type="button" onclick="location.href='{% url 'pybo:index' %}' ">Q&A</button>
        {% endif %}
    </nav>

</body>
</html>

30days/templates/navbar.html
<!-- 네비게이션바 -->
<nav>
    <!-- 로그인 -->
    {% if user.is_authenticated %}
        <button type="button" onclick="location.href='{% url 'common:logout' %}' ">{{ user.username }} (로그아웃)</button>
    {% else %}
        <button type="button" onclick="location.href='{% url 'common:login' %}' ">login</button>
    {% endif %}

    <!-- Q&A 게시판 -->
    <button type="button" onclick="location.href='{% url 'pybo:index' %}' ">Q&A</button>
</nav>